### ISSUE TITLE
登录限制怎么解决的

### ISSUE THREAD

**Issue by ghost** [zhaoweilong007/zhihuCrawler#1]
{"error":{"need_login":true,"redirect":"https:\/\/www.zhihu.com\/account\/unhuman?type=unhuman&message=%E7%B3%BB%E7%BB%9F%E7%9B%91%E6%B5%8B%E5%88%B0%E6%82%A8%E7%9A%84%E7%BD%91%E7%BB%9C%E7%8E%AF%E5%A2%83%E5%AD%98%E5%9C%A8%E5%BC%82%E5%B8%B8%EF%BC%8C%E4%B8%BA%E4%BF%9D%E8%AF%81%E6%82%A8%E7%9A%84%E6%AD%A3%E5%B8%B8%E8%AE%BF%E9%97%AE%EF%BC%8C%E8%AF%B7%E8%BE%93%E5%85%A5%E9%AA%8C%E8%AF%81%E7%A0%81%E8%BF%9B%E8%A1%8C%E9%AA%8C%E8%AF%81%E3%80%82%E8%8B%A5%E9%A2%91%E7%B9%81%E5%87%BA%E7%8E%B0%E6%AD%A4%E9%A1%B5%E9%9D%A2%EF%BC%8C%E5%8F%AF%E5%B0%9D%E8%AF%95%E7%99%BB%E5%BD%95%E5%90%8E%E8%AE%BF%E9%97%AE%E7%9F%A5%E4%B9%8E%E3%80%82&need_login=true","code":40352,"message":"系统监测到您的网络环境存在异常，为保证您的正常访问，请输入验证码进行验证。若频繁出现此页面，可尝试登录后访问知乎。"}}

**Comment by zhaoweilong007** [comment]
@evolution-ant 没有好的办法，可以尝试使用多个代理
